# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad52cbd1e22a3e993fc1b19889d40f1732c4115fd678f538c36784155e96d8438ccf79e78ec3356aa1a88dd7436823d26397e6fb6c9aedfb436a198d03b42bff

test:
  secret_key_base: 361552a8abd785f2ed82726af7212f93bc2fb03aaa23465f5c3dbf1466c2e40536c1b888f2f6f510287ffa87cd4610422a8231b1fb0c07d70f993dd0482d8153

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
